-- MySQL Script generated by MySQL Workbench
-- Tue Jul 18 15:16:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hay_boeing
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hay_boeing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hay_boeing` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hay_boeing` ;

-- -----------------------------------------------------
-- Table `hay_boeing`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hay_boeing`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullName` VARCHAR(255) NOT NULL,
  `role` ENUM('user', 'admin') NOT NULL DEFAULT 'user',
  `email` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `jwt_ac_token` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hay_boeing`.`objects_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hay_boeing`.`objects_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `price` FLOAT(10) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hay_boeing`.`objects_size_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hay_boeing`.`objects_size_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hay_boeing`.`flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hay_boeing`.`flights` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `number` VARCHAR(255) NOT NULL,
  `date_time` DATETIME NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `flightscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hay_boeing`.`objects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hay_boeing`.`objects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `objects_list_id` INT NOT NULL,
  `object_numer` VARCHAR(255) NOT NULL,
  `objects_size_list_id` INT NOT NULL,
  `flights_id` INT NOT NULL,
  `date_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_objects_objects_list_idx` (`objects_list_id` ASC) VISIBLE,
  INDEX `fk_objects_objects_size_list1_idx` (`objects_size_list_id` ASC) VISIBLE,
  INDEX `fk_objects_flights1_idx` (`flights_id` ASC) VISIBLE,
  CONSTRAINT `fk_objects_objects_list`
    FOREIGN KEY (`objects_list_id`)
    REFERENCES `hay_boeing`.`objects_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_objects_objects_size_list1`
    FOREIGN KEY (`objects_size_list_id`)
    REFERENCES `hay_boeing`.`objects_size_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_objects_flights1`
    FOREIGN KEY (`flights_id`)
    REFERENCES `hay_boeing`.`flights` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
